import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const robotoMono = Roboto_Mono({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${robotoMono} antialiased`}>{children}</body>
            <Toaster />
        </html>
    );
}
